Traceback (most recent call last):
  File "/Users/angadhnanjangud/opt/anaconda3/envs/computational-mechanics-example/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/angadhnanjangud/opt/anaconda3/envs/computational-mechanics-example/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/angadhnanjangud/opt/anaconda3/envs/computational-mechanics-example/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/angadhnanjangud/opt/anaconda3/envs/computational-mechanics-example/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/angadhnanjangud/opt/anaconda3/envs/computational-mechanics-example/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/angadhnanjangud/opt/anaconda3/envs/computational-mechanics-example/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/angadhnanjangud/opt/anaconda3/envs/computational-mechanics-example/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
B.dcm(A)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[11], line 1[0m
[0;32m----> 1[0m [43mB[49m[38;5;241;43m.[39;49m[43mdcm[49m[43m([49m[43mA[49m[43m)[49m

File [0;32m~/opt/anaconda3/envs/computational-mechanics-example/lib/python3.8/site-packages/sympy/physics/vector/frame.py:531[0m, in [0;36mReferenceFrame.dcm[0;34m(self, otherframe)[0m
[1;32m    529[0m [38;5;28;01mif[39;00m otherframe [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39m_dcm_cache:
[1;32m    530[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_dcm_cache[otherframe]
[0;32m--> 531[0m flist [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_dict_list[49m[43m([49m[43motherframe[49m[43m,[49m[43m [49m[38;5;241;43m0[39;49m[43m)[49m
[1;32m    532[0m outdcm [38;5;241m=[39m eye([38;5;241m3[39m)
[1;32m    533[0m [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m [38;5;28mrange[39m([38;5;28mlen[39m(flist) [38;5;241m-[39m [38;5;241m1[39m):

File [0;32m~/opt/anaconda3/envs/computational-mechanics-example/lib/python3.8/site-packages/sympy/physics/vector/frame.py:328[0m, in [0;36mReferenceFrame._dict_list[0;34m(self, other, num)[0m
[1;32m    325[0m     [38;5;28;01mreturn[39;00m possible_connecting_paths[[38;5;241m0[39m]  [38;5;66;03m# selects the shortest path[39;00m
[1;32m    327[0m msg [38;5;241m=[39m [38;5;124m'[39m[38;5;124mNo connecting [39m[38;5;132;01m{}[39;00m[38;5;124m path found between [39m[38;5;132;01m{}[39;00m[38;5;124m and [39m[38;5;132;01m{}[39;00m[38;5;124m.[39m[38;5;124m'[39m
[0;32m--> 328[0m [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(msg[38;5;241m.[39mformat(connect_type[num], [38;5;28mself[39m[38;5;241m.[39mname, other[38;5;241m.[39mname))

[0;31mValueError[0m: No connecting orientation path found between B and A.

